version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: nginx
     group: nginx
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/stop_nginx.sh
      runas: root
   AfterInstall:
    - location: scripts/start_nginx.sh
      runas: root
